sudo: true
dist: xenial
language: python
python:
    - 3.6
    - 3.7
git:
  depth: false
addons:
  apt:
    sources:
      - sourceline: 'ppa:tah83/secp256k1'
    packages:
      - libsecp256k1-0
before_install:
  - git tag
install:
  - pip install -r contrib/requirements/requirements-travis.txt
cache:
  - pip: true
  - directories:
    - /tmp/electrum-rvn-build
script:
    - echo "tests skipped"
after_success:
    - if [ "$TRAVIS_BRANCH" = "master" ]; then pip install requests && contrib/make_locale; fi
    - coveralls
jobs:
  include:
    - stage: binary builds
      sudo: true
      language: c
      python: false
      env:
        - TARGET_OS=Windows
      services:
        - docker
      install:
        - sudo docker build  --no-cache -t electrum-rvn-wine-builder-img ./contrib/build-wine/docker/
      script:
        - sudo docker run --name electrum-rvn-wine-builder-cont -v $PWD:/opt/wine64/drive_c/electrum-rvn --rm --workdir /opt/wine64/drive_c/electrum-rvn/contrib/build-wine electrum-rvn-wine-builder-img ./build.sh
      after_success: true
    - os: osx
      language: c
      env:
        - TARGET_OS=macOS
      python: false
      install:
        - git fetch --all --tags
      script: ./contrib/build-osx/make_osx
      after_script: ls -lah dist && md5 dist/*
      after_success: true
    - stage: release check
      install:
          - git fetch --all --tags
      script:
        - ./contrib/deterministic-build/check_submodules.sh
      after_success: true
      if: tag IS present
